version: '3.8'

services:
  educore-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educore_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
